source 'https://rubygems.org'

ruby '2.1.1'

gem 'rails', '4.0.1'

gem 'puma'

gem 'sass-rails', '~> 4.0.0'

gem 'uglifier', '>= 1.3.0'

gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 1.2'

gem 'font-awesome-rails'

gem 'd3-rails'

group :doc do
  gem 'sdoc', require: false
end

gem 'rails_12factor', :groups => [:development, :production]

group :development, :test do
  gem 'dotenv-rails'
end
